### ISSUE TITLE
Typo in AppStream metadata

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/page.codeberg.JakobDev.jdFlatpakSnapshot#3]
[This](https://codeberg.org/JakobDev/jdFlatpakSnapshot/src/branch/main/deploy/page.codeberg.JakobDev.jdFlatpakSnapshot.metainfo.xml#L5) should probably be Flatpak, not Flatpal. :-) I sadly do not have a Codeberg account to fix it.

**Comment by JakobDev** [comment]
It has now been fixed. Thanks.
